version: '3.8'

services:
  postgres:
    container_name: nest-postgres
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=nest

  cache:
    container_name: nest-redis
    image: redis
    ports:
      - 6379:6379